//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilities
    {
        public int FacilitiesID { get; set; }
        public Nullable<int> FacilitiesWashing { get; set; }
        public Nullable<int> Facilitiesairconditioner { get; set; }
        public Nullable<int> Facilitieswardrobe { get; set; }
        public Nullable<int> FacilitiesTV { get; set; }
        public Nullable<int> FacilitiesRefrigerator { get; set; }
        public Nullable<int> FacilitiesBed { get; set; }
        public Nullable<int> FacilitiesWIFI { get; set; }
        public Nullable<int> FacilitiesNaturalgas { get; set; }
        public Nullable<int> FacilitiesHeater { get; set; }
        public Nullable<int> FacilitiesHeating { get; set; }
        public Nullable<int> LeaseID { get; set; }
    
        public virtual Lease Lease { get; set; }
    }
}
