//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseEntities : DbContext
    {
        public HouseEntities()
            : base("name=HouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<LCollection> LCollection { get; set; }
        public virtual DbSet<Lease> Lease { get; set; }
        public virtual DbSet<LImg> LImg { get; set; }
        public virtual DbSet<Salesman> Salesman { get; set; }
        public virtual DbSet<SCollection> SCollection { get; set; }
        public virtual DbSet<Sell> Sell { get; set; }
        public virtual DbSet<Selling> Selling { get; set; }
        public virtual DbSet<SImg> SImg { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Userd> Userd { get; set; }
    }
}
