//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salesman()
        {
            this.Lease = new HashSet<Lease>();
            this.Sell = new HashSet<Sell>();
        }
    
        public int SalesmanID { get; set; }
        public string SalesmanName { get; set; }
        public Nullable<int> SalesmanSex { get; set; }
        public string SalesmanPhone { get; set; }
        public string SalesmanEmail { get; set; }
        public string SalesmanVX { get; set; }
        public string SalesmanPassword { get; set; }
        public string Photo { get; set; }
        public Nullable<int> UState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lease> Lease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sell { get; set; }
    }
}
